### ISSUE TITLE
Mixing Upper and Lowercase breaks autocomplete

### ISSUE THREAD

**Issue by boktai1000** [darfink/ItemAutocomplete#5]
See my examples here- If you use proper casing for an item such as [Felsteel Gloves] you'll find the item in the lookup. If you use all lowercase such as [felsteel gloves] you'll also find it. But if you mix upper and lowercase, it won't find the item - such as [Felsteel gloves] you won't find anything.

Here's some screenshots replicating this behavior-

Edit: I should also note that when mix casing for an item such as Felsteel Gloves it works when you capitlize the G on Gloves, but when you replace it with a lowercase g then it doesn't work. That's what the issue is here - hopefully this makes sense!

![no autocomplete](https://user-images.githubusercontent.com/9054563/123354893-2cafe600-d52a-11eb-8594-b9500e443ec6.PNG)

![autocomplete lowercase](https://user-images.githubusercontent.com/9054563/123354901-2faad680-d52a-11eb-80e6-93e3a54ac3f0.PNG)

![with autocomplete](https://user-images.githubusercontent.com/9054563/123354904-31749a00-d52a-11eb-87c2-3f5fe3bc1138.PNG)

**Comment by darfink** [comment]
Hi @boktai1000! Thanks for your consideration, but the behavior you're describing is working as intended.
As can be seen here, on the Curseforge project page, please note the last item — smart case:

![image](https://user-images.githubusercontent.com/1612390/123538961-8a654d80-d737-11eb-8aa2-71a61ded1594.png)

Smart casing is fairly common within text interaction tools, since it provides "best of both worlds ™️". It allows you to ignore casing in the majority of cases, but it can still be utilized when additional filtering is necessary. This makes, e.g., filtering by initials very effective. <kbd>[BNM</kbd> → `Blade of the New Moon`; this query would, if treated case insensitively, not provide context-aware auto completions.

With that said, if you prefer queries to always be treated case-insensitively, this can be configured in-game:
![image](https://i.imgur.com/XFTxcPv.png)
